name: badaqmon
base: core22
version: "2.0.0"
summary: DAQ for external balance # 79 char long summary
description: |
  Application in data acquisition for external balance. All data are monitored real time consisting of force and momen. This application depends on BADAQ instrumentation separately.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  badaqmon:
    command: usr/bin/badaqmon
    desktop: usr/share/applications/badaqmon.desktop
    extensions: [gnome]
    plugs:
      - network
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      npm install
      rustup default stable
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      ls $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      ls $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps/
      sed -i -e "s|Icon=badaqmon|Icon=/usr/share/icons/hicolor/32x32/apps/badaqmon.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/badaqmon.desktop
